---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot-mizucoffee-net
spec:
  replicas: 6
  selector:
    matchLabels:
      role: dot-mizucoffee-net
  template:
    metadata:
      labels:
        role: dot-mizucoffee-net
    spec:
      topologySpreadConstraints:
        - topologyKey: node
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: dot-mizucoffee-net
      containers:
        - name: dot-mizucoffee-net
          image: mizucoffee/static_serve:v1.0-node16
          imagePullPolicy: Always
          env:
          - name: GITHUB_REPO
            value: https://github.com/mizucoffee/dot.mizucoffee.net
          - name: PUBLISH_DIR
            value: build
          - name: BUILD_CMD
            value: npm i; npm run build
---
apiVersion: v1
kind: Service
metadata:
  name: dot-mizucoffee-net-svc
spec:
  type: ClusterIP
  ports:
    - name: "nginx-port"
      protocol: "TCP"
      port: 80
  selector:
    role: dot-mizucoffee-net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dot-mizucoffee-net-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: dot.mizucoffee.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: dot-mizucoffee-net-svc
                port:
                  number: 80
