---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizu-coffee
spec:
  replicas: 6
  selector:
    matchLabels:
      role: mizu-coffee
  template:
    metadata:
      labels:
        role: mizu-coffee
    spec:
      topologySpreadConstraints:
        - topologyKey: node
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: mizu-coffee
      containers:
        - name: mizu-coffee
          image: mizucoffee/static_serve:v1.0-node16
          imagePullPolicy: Always
          env:
          - name: GITHUB_REPO
            value: https://github.com/mizucoffee/mizu.coffee
          - name: PUBLISH_DIR
            value: dest
          - name: BUILD_CMD
            value: npm i; npm run build
---
apiVersion: v1
kind: Service
metadata:
  name: mizu-coffee-svc
spec:
  type: ClusterIP
  ports:
    - name: "nginx-port"
      protocol: "TCP"
      port: 80
  selector:
    role: mizu-coffee
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mizu-coffee-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: mizu.coffee
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mizu-coffee-svc
                port:
                  number: 80
