apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-files-pv
  labels:
    name: redmine-files-pv
spec:
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.105.0
    path: /nfs/redmine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
  selector:
    matchLabels:
      name: redmine-files-pv