apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  stubDomains: |
    {"l.mizucoffee.com": ["192.168.104.1"]}
  upstreamNameservers: |
    ["192.168.105.0", "8.8.8.8", '8.8.4.4"]