---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mokumoku
spec:
  replicas: 6
  selector:
    matchLabels:
      role: mokumoku
  template:
    metadata:
      labels:
        role: mokumoku
    spec:
      topologySpreadConstraints:
        - topologyKey: node
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: mokumoku
      containers:
        - name: mokumoku
          image: mizucoffee/mokumoku:v1.0
          imagePullPolicy: IfNotPresent
          env:
          - name: token
            valueFrom:
              secretKeyRef:
                name: mokumoku-secret
                key: slack_token
          - name: channel
            valueFrom:
              secretKeyRef:
                name: mokumoku-secret
                key: slack_channel
---
apiVersion: v1
kind: Service
metadata:
  name: mokumoku-svc
spec:
  type: ClusterIP
  ports:
    - name: "express-port"
      protocol: "TCP"
      port: 3000
  selector:
    role: mokumoku
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mokumoku-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
    - host: mokumoku.mizucoffee.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mokumoku-svc
                port:
                  number: 3000
