---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keshigo
spec:
  replicas: 6
  selector:
    matchLabels:
      role: keshigo
  template:
    metadata:
      labels:
        role: keshigo
    spec:
      topologySpreadConstraints:
        - topologyKey: node
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: keshigo
      containers:
        - name: keshigo
          image: mizucoffee/keshigo:v1.0
          imagePullPolicy: Always
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: keshigo-secret
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: keshigo-svc
spec:
  type: ClusterIP
  ports:
    - name: "sinatra-port"
      protocol: "TCP"
      port: 4567
  selector:
    role: keshigo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keshigo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Connection "Upgrade";
spec:
  rules:
    - host: keshigo.mizucoffee.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: keshigo-svc
                port:
                  number: 4567
