---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyaru-pyon
spec:
  replicas: 6
  selector:
    matchLabels:
      role: gyaru-pyon
  template:
    metadata:
      labels:
        role: gyaru-pyon
    spec:
      topologySpreadConstraints:
        - topologyKey: node
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: gyaru-pyon
      containers:
        - name: gyaru-pyon
          image: mizucoffee/gyaru-pyon:v1.0
          imagePullPolicy: Always
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: database_url
          - name: WATSON_API_KEY
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: watson_api_key
          - name: WATSON_TONE_ANALYZER_URL
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: watson_tone_analyzer_url
          - name: DEEPL_TOKEN
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: deepl_token
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: session_secret
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: jwt_secret
          - name: AITALK_USERNAME
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: aitalk_username
          - name: AITALK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gyaru-pyon-secret
                key: aitalk_password
---
apiVersion: v1
kind: Service
metadata:
  name: gyaru-pyon-svc
spec:
  type: ClusterIP
  ports:
    - name: "express-port"
      protocol: "TCP"
      port: 3000
  selector:
    role: gyaru-pyon
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gyaru-pyon-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: gyaru-pyon.mizucoffee.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: gyaru-pyon-svc
                port:
                  number: 3000
