---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      role: dotmanager
  template:
    metadata:
      labels:
        role: dotmanager
    spec:
      containers:
        - name: dotmanager
          image: mizucoffee/dotmanager:v1.0
          env:
          - name: TZ
            value: Asia/Tokyo
          - name: DC_CRON
            value: 30 7,11,13,15,17,21 * * *
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: dotmanager-secret
                key: database_url
          - name: DC_URL
            valueFrom:
              secretKeyRef:
                name: dotmanager-secret
                key: dc_url
          - name: DC_IFTTT
            valueFrom:
              secretKeyRef:
                name: dotmanager-secret
                key: dc_ifttt
          - name: DC_ID
            valueFrom:
              secretKeyRef:
                name: dotmanager-secret
                key: dc_id
          - name: DC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dotmanager-secret
                key: dc_password
