apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: develop@mizucoffee.net

    privateKeySecretRef:
      name: letsencrypt-pks

    solvers:
    - selector: {}
      dns01:
        cloudDNS:
          project: mizucoffee-net-dns
          serviceAccountSecretRef:
            name: letsencrypt-secret
            key: key.json
